name: Bug Report
description: Report a bug or crash you encountered
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug with Faroquin, the mod manager for Balatro. Please provide as many details as you can to help us diagnose and fix the problem.
  - type: dropdown
    id: faroquin_version
    attributes:
      label: Are you using the latest version of Faroquin?
      description: If you're not up to date, please download and try the latest version before submitting.
      options:
        - No, I need to update.
        - Yes, I'm on the latest stable release of Faroquin.
        - Yes, I'm on the latest pre-release of Faroquin.
    validations:
      required: true
  - type: dropdown
    id: faroquin_type
    attributes:
      label: What type of release are you using?
      description: Choose the operating system and version of Faroquin you are running.
      options:
        - Unselected
        - Windows x64
        - Windows Arm64
    validations:
      required: true
  - type: textarea
    id: mods_involved
    attributes:
      label: Which mods are involved?
      description: (Optional) List the mods related to the issue. Include links or repositories if applicable.
    validations:
      required: false
  - type: textarea
    id: balatro_version
    attributes:
      label: What version of Balatro are you using?
      description: Let us know the specific version of Balatro you're working with.
    validations:
      required: true
  - type: textarea
    id: what_happened
    attributes:
      label: What went wrong?
      description: Describe the issue in detail. What did you expect to happen instead? Include steps to reproduce the problem, if possible.
      placeholder: Explain the problem and how to recreate it.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log file output
      description: |
        Attach your `main.log` file, located at `C:\Users\%UserProfile%\AppData\Roaming\faroquin\logs\main.log`. Text is preferred over screenshots, as it's easier to analyze.
    validations:
      required: false
