name: Enhancement Request
description: Suggest a new feature or an improvement for Faroquin.
title: "[Enhancement]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest an enhancement for Faroquin! Please fill out the details below to help us better understand your idea.
  - type: textarea
    id: enhancement_summary
    attributes:
      label: What would you like to see improved or added?
      description: Briefly describe your suggestion or feature idea.
      placeholder: Example: Add support for sorting mods by install date.
  - type: textarea
    id: current_behavior
    attributes:
      label: What is the current behavior or limitation?
      description: Explain what currently happens in Faroquin that your suggestion would improve upon.
      placeholder: Example: There’s no way to see when mods were installed.
  - type: textarea
    id: desired_behavior
    attributes:
      label: What is the desired behavior or outcome?
      description: Explain what the feature or improvement would do and how it would work.
      placeholder: Example: A column in the mod manager that shows the installation date for each mod.
  - type: dropdown
    id: complexity
    attributes:
      label: How complex is this change?
      description: Estimate the complexity of implementing this feature or improvement.
      options:
        - Low (e.g., UI adjustment or small addition)
        - Medium (e.g., adding a new module or functionality)
        - High (e.g., significant changes to existing systems)
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context or screenshots
      description: (Optional) Add any extra details, context, or visual aids to clarify your request.
      placeholder: Include screenshots, diagrams, or links to references if applicable.
